### PR TITLE
Use tox

### PR DESCRIPTION
**Pull request by rockymeza**

### CODE REVIEW

**Comment by rockymeza** [comment]
I based the .travis.yml on django-authtools, but then used the matrix clause from [pip](https://github.com/pypa/pip/blob/166f3d20e27f06c1ca74d30ec6ceed688f295b47/.travis.yml), which has two advantages:

1.  works on python 3.5
2.  displays the python version better on the travis website

**Comment by pipermerriam** [comment]
:+1: looks nice.  You might add a `flake8` job while you're in there but I'm not sure how you feel about code linting as part of CI

**Comment by rockymeza** [comment]
You can add flake8 in a different PR. ;) I'd be up for that.

-rocky

**Comment by rockymeza** [comment]
ping @jxcl @gavinwahl

**Comment by gavinwahl** [comment]
@rockymeza doesn't matter to me -- I think you have the appropriate permissions to merge this

**Comment by rockymeza** [comment]
@pipermerriam do you have an example of a flake8 setup?

**Comment by pipermerriam** [comment]
Yeah.  Look at flex under my github

**Pull request merged**
